##  Dockerfile文件格式

# This dockerfile uses the ubuntu image
# VERSION 2 - EDITION 1
# Author: docker_user
# Command format: Instruction [arguments / command] ..
 
# 1、第一行必须指定 基础镜像信息
FROM mycentos
 
# 2、维护者信息
MAINTAINER chen0625 wchen0625@163.com
 
# 3、镜像操作指令
RUN yum -y install python

# 4、容器启动执行指令
# CMD 
